CREATE TABLE COMPANY (
    COMPANY_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT chk_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    AGE INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE COMPANY
RENAME COLUMN ID TO COMPANY_ID;
ALTER TABLE COMPANY
    ALTER COLUMN created_at TYPE TIMESTAMP;
  
CREATE TABLE agent (
    AGENT_ID SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    no_of_successful_leads INT DEFAULT 0,
    company_id INT NOT NULL,
    CONSTRAINT chk_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    FOREIGN KEY (company_id) REFERENCES company(COMPANY_ID)
);
ALTER TABLE AGENT
RENAME COLUMN ID TO AGENT_ID;

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PHONE_NO VARCHAR(15) NOT NULL UNIQUE CHECK (PHONE_NO ~* '^\+?[1-9]\d{1,14}$'),
    ACCOUNT_BALANCE DECIMAL(12, 2) NOT NULL CHECK (ACCOUNT_BALANCE >= 0),
    CREDIT_SCORE INTEGER NOT NULL CHECK (CREDIT_SCORE >= 300 AND CREDIT_SCORE <= 850),
    CONSTRAINT chk_email_format CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE LEAD (
    LEAD_ID SERIAL PRIMARY KEY,
    REFERENCE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    AGENT_ID INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'HOLD')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (AGENT_ID) REFERENCES AGENT(AGENT_ID) ON DELETE CASCADE
);

select * from customers;
select * from agent;
select * from company;
select * from lead;