USE JDBC;
CREATE TABLE IF NOT EXISTS STUDENT(
	USER_ID INT PRIMARY KEY,
    USER_NAME VARCHAR(25)
);
SELECT * FROM STUDENT;


INSERT INTO STUDENT(USER_ID, USER_NAME)
	VALUES
		(1,"RANU"),
        (2,"MANU"),
        (3,"ANUPURBA"),
        (4,"ADITI"),
        (5,"ABHYAM");
        
SHOW VARIABLES WHERE Variable_name = 'port'
